### ISSUE TITLE
Buggy quantities during insertion

### ISSUE THREAD

**Issue by pdobbelaere** [molmod/psiflow#53]
When a GPAW single point fails due to timeout (although it might be more general), the `insert_quantities` call inside `Dataset.evaluate` fails with
```
Traceback (most recent call last):
  File "/kyukon/data/gent/vo/000/gvo00003/vsc43633/micromamba/envs/test_psiflow/lib/python3.10/site-packages/parsl/dataflow/dflow.py", line 344, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/kyukon/data/gent/vo/000/gvo00003/vsc43633/micromamba/envs/test_psiflow/lib/python3.10/site-packages/parsl/dataflow/dflow.py", line 614, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/kyukon/data/gent/vo/000/gvo00003/vsc43633/micromamba/envs/test_psiflow/lib/python3.10/site-packages/parsl/app/errors.py", line 117, in reraise
    raise v
  File "/kyukon/data/gent/vo/000/gvo00003/vsc43633/micromamba/envs/test_psiflow/lib/python3.10/site-packages/parsl/app/errors.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/kyukon/data/gent/vo/000/gvo00003/vsc43633/micromamba/envs/test_psiflow/lib/python3.10/site-packages/psiflow/data/utils.py", line 185, in _insert_quantities
    geometry.per_atom.forces[mask[:natoms]] = arrays[j][i, mask, :]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1 but corresponding boolean dimension is 76
```
I dropped in some print statements which gave
```
2024-11-27 18:27:38.361687 | in "_insert_quantities"
quantities: ('energy', 'forces')
arrays: [array([nan], dtype=float32), array([[[nan, nan, nan]]], dtype=float32)]
data: None
inputs: [<File at 0x7f58585146a0 [...] filename=data_000000.xyz>]
```
Since `_insert_quantities` is not passed a `data` argument, it reads `geometries` from `inputs` ([here](https://github.com/molmod/psiflow/blob/720fee3219260ff370e274ad579f103d2257871a/psiflow/data/utils.py#L164C1-L166C43)), which is the original  `Dataset`  I think. Then it loops over all `geometries` - rejecting `Nullstates` - and tries to index `array([[[nan, nan, nan]]]` with a `mask` that clearly does not fit.

I assume that the `forces` array has shape `[n_geometries, len(largest_geometry), 3]`, so sometimes [this line](https://github.com/molmod/psiflow/blob/720fee3219260ff370e274ad579f103d2257871a/psiflow/data/utils.py#L185C17-L185C80) will simply copy a bunch of `NaNs` into the `geometry` of the failed single point, which is probably fine. Here, it borks the Parsl workflow.

On a separate note, my prints were called thrice
```
2024-11-27 18:27:38.361687 | in "_insert_quantities"
[...]

2024-11-27 18:27:38.367676 | in "_insert_quantities"
[...]

2024-11-27 18:27:38.371145 | in "_insert_quantities"
[...]
```
where every `[...]` block is identical. Seems like  `_insert_quantities` is called 3 times, or could there be a different reason for this duplication?

[files.zip](https://github.com/user-attachments/files/17938508/files.zip)

**Comment by svandenhaute** [comment]
After an offline discussion with @pdobbelaere :

- the `IndexError` in the `insert_quantities` app is implicitly caused by suboptimal behavior from the `evaluate` join_app in `psiflow.reference`. This behavior is fixed in 0dfbb35 and should also fix this bug.
- the error appears three times because the operation of inserting quantities is a Parsl app, which will be retried a given number of times as specified in the `.yaml` input. By default, there are two retries, so three total executions of a failing app.
